/**
 * Permission constants for the application
 */
const PERMISSIONS = {
  
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_USERS: 'MANAGE_USERS',
  
  
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  
  
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  
  
  VIEW_CATEGORIES: 'VIEW_CATEGORIES',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
  
  
  VIEW_STOCK_MOVEMENTS: 'VIEW_STOCK_MOVEMENTS',
  MANAGE_STOCK_MOVEMENTS: 'MANAGE_STOCK_MOVEMENTS',
  
  
  VIEW_ORDERS: 'VIEW_ORDERS',
  MANAGE_ORDERS: 'MANAGE_ORDERS',
  
  
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  
  
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  
  
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_SALES_REPORT: 'VIEW_SALES_REPORT',
  VIEW_STOCK_REPORT: 'VIEW_STOCK_REPORT',
  VIEW_CUSTOMER_REPORT: 'VIEW_CUSTOMER_REPORT',
  
  
  VIEW_AI_ANALYTICS: 'VIEW_AI_ANALYTICS',
  MANAGE_AI_ANALYTICS: 'MANAGE_AI_ANALYTICS',
  
  
  MANAGE_INVENTORY: 'MANAGE_INVENTORY'
};

/**
 * Role permission mappings
 */
const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.VIEW_STOCK_MOVEMENTS,
    PERMISSIONS.MANAGE_STOCK_MOVEMENTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SALES_REPORT,
    PERMISSIONS.VIEW_STOCK_REPORT,
    PERMISSIONS.VIEW_CUSTOMER_REPORT,
    PERMISSIONS.VIEW_AI_ANALYTICS,
    PERMISSIONS.MANAGE_INVENTORY
  ],
  WAREHOUSE: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_STOCK_MOVEMENTS,
    PERMISSIONS.MANAGE_STOCK_MOVEMENTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.MANAGE_INVENTORY
  ],
  SALES: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.VIEW_SALES_REPORT
  ]
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS
}; 